config/routes.rb
Railbook::Application.routes.draw do
  resources :fan_comments

  resources :reviews

  resources :authors

  resources :users

  resources :books

  match ':controller(/:action(/:id))', via: [:get, :post, :patch]

end

app/models/fan_comment.rb
class FanComment < ActiveRecord::Base
end

app/controllers/fan_comments_controller.rb
class FanCommentsController < ApplicationController
  before_action :set_fan_comment, only: [:show, :edit, :update, :destroy]

  # GET /fan_comments
  # GET /fan_comments.json
  def index
    @fan_comments = FanComment.all
  end

  # GET /fan_comments/1
  # GET /fan_comments/1.json
  def show
  end

  # GET /fan_comments/new
  def new
    @fan_comment = FanComment.new
  end

  # GET /fan_comments/1/edit
  def edit
  end

  # POST /fan_comments
  # POST /fan_comments.json
  def create
    @fan_comment = FanComment.new(fan_comment_params)

    respond_to do |format|
      if @fan_comment.save
        format.html { redirect_to @fan_comment, notice: 'Fan comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fan_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fan_comments/1
  # PATCH/PUT /fan_comments/1.json
  def update
    respond_to do |format|
      if @fan_comment.update(fan_comment_params)
        format.html { redirect_to @fan_comment, notice: 'Fan comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fan_comments/1
  # DELETE /fan_comments/1.json
  def destroy
    @fan_comment.destroy
    respond_to do |format|
      format.html { redirect_to fan_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan_comment
      @fan_comment = FanComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_comment_params
      params.require(:fan_comment).permit(:author_no, :name, :body, :deleted)
    end
end

app/helpers/fan_comments_helper.rb
module FanCommentsHelper
end

app/views/fan_comments/_form.html.erb
<%= form_for(@fan_comment) do |f| %>
  <% if @fan_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fan_comment.errors.count, "error") %> prohibited this fan_comment from being saved:</h2>

      <ul>
      <% @fan_comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author_no %><br>
    <%= f.number_field :author_no %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fan_comments/edit.html.erb
<h1>Editing fan_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fan_comment %> |
<%= link_to 'Back', fan_comments_path %>

app/views/fan_comments/index.html.erb
<h1>Listing fan_comments</h1>

<table>
  <thead>
    <tr>
      <th>Author no</th>
      <th>Name</th>
      <th>Body</th>
      <th>Deleted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fan_comments.each do |fan_comment| %>
      <tr>
        <td><%= fan_comment.author_no %></td>
        <td><%= fan_comment.name %></td>
        <td><%= fan_comment.body %></td>
        <td><%= fan_comment.deleted %></td>
        <td><%= link_to 'Show', fan_comment %></td>
        <td><%= link_to 'Edit', edit_fan_comment_path(fan_comment) %></td>
        <td><%= link_to 'Destroy', fan_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fan comment', new_fan_comment_path %>

app/views/fan_comments/new.html.erb
<h1>New fan_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', fan_comments_path %>

app/views/fan_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author no:</strong>
  <%= @fan_comment.author_no %>
</p>

<p>
  <strong>Name:</strong>
  <%= @fan_comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @fan_comment.body %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @fan_comment.deleted %>
</p>

<%= link_to 'Edit', edit_fan_comment_path(@fan_comment) %> |
<%= link_to 'Back', fan_comments_path %>